import subprocess
import os

fake_campfire_file = "/ender_campfire_fire.png"
fake_campfire_dir = "src/main/resources/assets/endergetic/textures/block"
processor_list_dir = "src/generated/resources/data/wetland_whimsy/worldgen/processor_list/"

# Creating a fake "ender_campfire_fire" texture, since datagen otherwise does not think that it exists
os.makedirs(fake_campfire_dir, exist_ok=True)
fake_img = open(fake_campfire_dir + fake_campfire_file, "w")

# Running the datagen
subprocess.run(["./gradlew", "rundata"])

# Removing the fake "ender_campfire_fire" texture
os.remove(fake_campfire_dir + fake_campfire_file)

# Removing the autogenerated processor lists, since those were written manually 
os.remove(processor_list_dir + "dungeon.json")
os.remove(processor_list_dir + "limestone_rubble.json")
