modLoader="javafml" # Maybe Kotlin could be considered in the future?
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://gitlab.com/junimods/Wetland-Whimsy/-/issues"

[[mods]]
modId="${mod_id}" 
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
authors="${mod_authors}"
description='''${mod_description}'''
credits = """\n
- Blemish Texture: Alganaut
- Nuke The Swamps: Quizzly
- Purple Trees: Skyllaremon
"""

# These are the complex things 
[[mixins]]
config="wetland_whimsy.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

# Dependencies 
[[dependencies.wetland_whimsy]]
	modId="neoforge"
	type="required"
	versionRange="${neo_version_range}"
	ordering="NONE"
	side="BOTH"

[[dependencies.wetland_whimsy]]
	modId="minecraft"
	type="required"
	versionRange="${minecraft_version_range}"
	ordering="NONE"
	side="BOTH"

[[dependencies.wetland_whimsy]]
	modId="supplementaries"
	type="optional"
	versionRange="(1,)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.wetland_whimsy]]
	modId="farmersdelight"
	type="optional"
	versionRange="(1,)"
	ordering="AFTER"
	side="BOTH"
